//! `shx config` — path, init, show, edit. Template matches docs/05-CLI-SPEC.md §4.

use std::env;
use std::fs;
use std::path::PathBuf;

use shx_config::load::{default_global_path, discover_project_toml};
use shx_config::{LoadInputs, load, load_from};

use crate::render::{EXIT_ERROR, EXIT_OK, EXIT_USAGE};
use crate::{Cli, ConfigCmd};

/// Commented default written by `shx config init`.
pub const DEFAULT_TEMPLATE: &str = r#"# shx.toml — generated by `shx config init`. All keys optional; defaults shown.

[backend]
mode = "local-first"                 # local | cloud | local-first
escalate_below_confidence = 0.6
local_slow_ms = 8000
complexity_skip_local = false        # ADR-009: measure before enabling

[backend.local]
kind = "ollama"
base_url = "http://127.0.0.1:11434"
model = "qwen3:14b"
keep_alive = "30m"
num_ctx = 4096
timeout_ms = 8000

[backend.cloud]
kind = "anthropic"                   # anthropic | openai-compat
model = "claude-sonnet-4-5"
api_key_env = "ANTHROPIC_API_KEY"    # we store the NAME, never the key
timeout_ms = 20000
# For openai-compat instead:
#   kind = "openai-compat"
#   base_url = "https://openrouter.ai/api/v1"
#   api_key_env = "OPENROUTER_API_KEY"

[memory]
enabled = true
path = ""                            # "" = OS default location
retention_days = 180
context = { recent = 10, relevance = 5, shell = 5, max_tokens = 1500 }
ingest_shell_history = false
redact_secrets = true                # do not set this to false

[safety]
warn_on_risk = true
exit_on_risk = false
refuse_multi_command_on_risk = true

[context]
os = "auto"                          # auto | macos | linux | windows
shell = "auto"
in_container = "auto"
prefer_docker = true
ports = [3000, 5432, 7000]
notes = ""                           # freeform, injected into PROFILE

[ui]
color = "auto"                       # auto | always | never
timing = false
update_check = "never"
candidates = 1

[snippets]
# remote = ""                        # P2: git repo of shared snippets
"#;

/// Dispatch `shx config <subcommand>`.
pub fn run(cmd: Option<&ConfigCmd>, cli: &Cli) -> i32 {
    match cmd {
        None => {
            eprintln!("shx config: expected path | show | get | set | edit | init");
            EXIT_USAGE
        }
        Some(ConfigCmd::Path) => path(cli),
        Some(ConfigCmd::Show { json }) => show(cli, *json),
        Some(ConfigCmd::Get { key }) => {
            eprintln!("shx config get {key}: not implemented yet");
            EXIT_ERROR
        }
        Some(ConfigCmd::Set { key, value }) => {
            eprintln!("shx config set {key} {value}: not implemented yet");
            EXIT_ERROR
        }
        Some(ConfigCmd::Edit) => edit(cli),
        Some(ConfigCmd::Init { force }) => init(cli, *force || cli.yes),
    }
}

/// Print discovered paths, lowest precedence first (global then project).
fn path(cli: &Cli) -> i32 {
    for p in config_paths(cli.config.as_deref()) {
        println!("{}", p.display());
    }
    EXIT_OK
}

fn config_paths(config_override: Option<&str>) -> Vec<PathBuf> {
    let mut v = Vec::new();
    if let Some(p) = config_override {
        v.push(PathBuf::from(p));
    } else {
        v.push(default_global_path());
    }
    if let Some(p) = discover_project_toml()
        && !v.iter().any(|e| e == &p)
    {
        v.push(p);
    }
    v
}

fn init(cli: &Cli, force: bool) -> i32 {
    let dest = config_paths(cli.config.as_deref())
        .into_iter()
        .next()
        .unwrap_or_else(default_global_path);
    if dest.exists() && !force {
        eprintln!(
            "shx: {} already exists; pass --force (or -y) to overwrite",
            dest.display()
        );
        return EXIT_USAGE;
    }
    if let Some(parent) = dest.parent()
        && let Err(e) = fs::create_dir_all(parent)
    {
        eprintln!("shx: failed to create {}: {e}", parent.display());
        return EXIT_ERROR;
    }
    if let Err(e) = fs::write(&dest, DEFAULT_TEMPLATE) {
        eprintln!("shx: failed to write {}: {e}", dest.display());
        return EXIT_ERROR;
    }
    match load_from(LoadInputs {
        global_toml: Some(DEFAULT_TEMPLATE),
        ..LoadInputs::default()
    }) {
        Ok(_) => {
            eprintln!("wrote {}", dest.display());
            EXIT_OK
        }
        Err(e) => {
            eprintln!("shx: wrote {} but validate failed: {e}", dest.display());
            EXIT_ERROR
        }
    }
}

fn show(cli: &Cli, json: bool) -> i32 {
    let flags = crate::pipeline::flag_overrides(cli);
    match load(flags) {
        Ok(loaded) => {
            for w in &loaded.warnings {
                eprintln!("warning: {w}");
            }
            if json {
                match serde_json::to_string(&loaded.config) {
                    Ok(s) => println!("{s}"),
                    Err(e) => {
                        eprintln!("shx: {e}");
                        return EXIT_ERROR;
                    }
                }
            } else {
                match serde_json::to_string_pretty(&loaded.config) {
                    Ok(s) => println!("{s}"),
                    Err(e) => {
                        eprintln!("shx: {e}");
                        return EXIT_ERROR;
                    }
                }
            }
            EXIT_OK
        }
        Err(e) => {
            eprintln!("shx: {e}");
            EXIT_USAGE
        }
    }
}

fn edit(cli: &Cli) -> i32 {
    let dest = config_paths(cli.config.as_deref())
        .into_iter()
        .next()
        .unwrap_or_else(default_global_path);
    if !dest.exists() {
        let code = init(cli, true);
        if code != EXIT_OK {
            return code;
        }
    }
    let editor = editor_bin();
    // T-SAFE-3: the program is $VISUAL / $EDITOR (or a platform default), never
    // derived from the user's natural-language intent. The only argument is the
    // config path we resolved.
    match std::process::Command::new(&editor).arg(&dest).status() {
        Ok(st) if st.success() => EXIT_OK,
        Ok(st) => {
            eprintln!("shx: {editor} exited {st}");
            EXIT_ERROR
        }
        Err(e) => {
            eprintln!("shx: failed to launch {editor}: {e}");
            EXIT_ERROR
        }
    }
}

fn editor_bin() -> String {
    env::var("VISUAL")
        .or_else(|_| env::var("EDITOR"))
        .unwrap_or_else(|_| {
            if cfg!(windows) {
                "notepad".into()
            } else {
                "vi".into()
            }
        })
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn default_template_validates() {
        load_from(LoadInputs {
            global_toml: Some(DEFAULT_TEMPLATE),
            ..LoadInputs::default()
        })
        .expect("DEFAULT_TEMPLATE must pass validate");
    }
}
